FROM scratch AS ctx

COPY ../shared/ /shared

FROM registry.opensuse.org/opensuse/tumbleweed:latest AS base

FROM base AS builder

RUN zypper install -y binutils cargo git go-md2man libostree-devel make rust

WORKDIR /home/build
RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    /ctx/shared/build.sh

FROM base AS system

COPY --from=builder /output /

RUN zypper install -y btrfs-progs cpio dosfstools dracut dracut e2fsprogs glib2 kernel-default kernel-firmware-all ostree skopeo systemd systemd-boot udev xfsprogs zstd libcrypto57

RUN --mount=type=tmpfs,dst=/tmp --mount=type=tmpfs,dst=/root \
    --mount=type=bind,from=ctx,source=/,target=/ctx \
    /ctx/shared/initramfs.sh

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    echo "HOME=/var/home" | tee -a "/etc/default/useradd" && \
    /ctx/shared/bootc-rootfs.sh

RUN rm -rf /usr/etc

LABEL containers.bootc 1

RUN bootc container lint
